print("Status: 200 OK\r\n")
print("Content-Type: text/html; charset=utf-8\r\n\r\n")

print("<html>\r\n")
print("<head>\r\n")
print("<title>Hello python!</title>\r\n")
print("</head>\r\n")
print("<body bgcolor=\"white\">\r\n")
print("<h1>Hello python!</h1>\r\n")
print("<hr>\r\n")
print("This is test page for python cgi.")
print("\r\n")
print("<hr>\r\n")
print("<center>HyeonSkkiDashi/1.0</center>\r\n")
print("</body>\r\n")
print("</html>")
